pool:
  vmImage: 'Ubuntu 16.04'

variables:
  configuration: 'Release'

steps:
- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core SDK 2.2.101'
  inputs:
    version: 2.2.101

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration $(configuration)'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(configuration)'
