variables:
  configuration: 'Release'
  
trigger:
- master

jobs:
- job: Test
  strategy:
    matrix:
      Ubuntu_16:
        imageName: ubuntu-16.04
      Ubuntu_18:
        imageName: ubuntu-18.04
  pool:
    vmImage: $(imageName)
  steps:
  - bash: |
      echo "/proc/diskstats:"
      cat /proc/diskstats

    displayName: Show stuff from procfs

  - task: UseDotNet@2
    displayName: 'Install .NET Core SDK 2.2.x'
    inputs:
      version: 2.2.x

  - task: UseDotNet@2
    displayName: 'Install .NET Core SDK 3.1.x'
    inputs:
      version: 3.1.x
  
  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: '**/*.csproj'
  
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: '**/*.csproj'
      arguments: '--configuration $(configuration)'
  
  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: test
      projects: '**/*Tests/*.csproj'
      arguments: '--configuration $(configuration)'
  
  - bash: |
      rm -r $(Build.ArtifactStagingDirectory)
      mkdir -p $(Build.ArtifactStagingDirectory)
    displayName: Cleanup artifacts directory
    
  - task: DotNetCoreCLI@2
    displayName: Pack
    inputs:
      command: pack
      packagesToPack: ProcFsCore/ProcFsCore.csproj
      configuration: $(configuration)
      nobuild: true
      
  - task: PublishBuildArtifacts@1
    displayName: Publish Artifact
    inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)
      artifactName: package

- job: Publish
  dependsOn:
  - Test
  condition: "and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))"
  pool:
    vmImage: windows-latest
  steps:
  - task: DownloadBuildArtifacts@0
    displayName: Download NuGet package Artifact
    inputs:
      artifactName: package
      downloadPath: $(Build.ArtifactStagingDirectory)

  - task: NuGetCommand@2
    displayName: Push to NuGet
    inputs:
      command: push
      packagesToPush: $(Build.ArtifactStagingDirectory)/package/*.nupkg
      nuGetFeedType: external
      publishFeedCredentials: NuGet.org
